site_name: Knowledge Wiki
site_url: https://lpverneck.github.io/notes/
repo_url: https://github.com/lpverneck/notes
site_description: Personal wiki with my reference material and notes.
site_author: Lucas Verneck

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book
  favicon: assets/icons.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
      primary: indigo
      accent: indigo

extra:
  social:
    - icon: simple/github
      link: https://github.com/lpverneck
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/lpverneck/

# copyright: Copyright &copy; 2024 Lucas Verneck

nav:
    - Home: index.md
    - Data Science:
      - Entropy: notebooks/entropy.ipynb
    - Web Development:
      - JavaScript: web-development/javascript.md
      - API's: web-development/apis.md
    - Software Engineering:
      - Environment Variables: software-engineering/env-vars.md
      - JSON: software-engineering/json.md
      - YAML: software-engineering/yaml.md
    # - Packages:
    #   - Poetry: packages/poetry.md
    #   - Dotenv: packages/dotenv.md
    #   - Test: notebooks/example_nbs.ipynb
    - Examples:
      - Jupyter Notebook: examples/example_nb.ipynb
      - Mkdocs Material: examples/example_mkdocs_material.md

plugins:
  - search:
  - mkdocs-jupyter:
      execute: False
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
